### PR TITLE
push lab1

### PR DESCRIPTION
**Pull request by saba024**

### CODE REVIEW

**Review by gmltA — CHANGES_REQUESTED** [review]
https://github.com/MiaSanRomen/PPO-Labs/pull/1#pullrequestreview-560043004

Good luck with that.

**Comment by saba024** [comment]
Переделал 1 лабораторную

**Review by gmltA — CHANGES_REQUESTED** [review]
У вас усё роўна не выканана заданне на лабараторную.

**Comment by saba024** [comment]
исправил

**Review by gmltA — CHANGES_REQUESTED** [review]
Заданне ўсё роўна не выканана. Чытайце яшчэ раз.

**Comment by saba024** [comment]
Все исправил. (3 different unit categories, 3 different units, Calculator-like num pad and two fields for original and converted values, 2 fragments, landscape and portrait, button, that will switch initial and converted values (and units) and vice-versa, button to copy current value to the clipboard near each data field,  files with code for each flavour) и версирование.  Все есть...

**Review by gmltA — APPROVED** [review]

**Pull request merged**
